# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_po', '0001_initial'),
        ('shared', '0001_initial'),
        ('transport', '0001_initial'),
        ('marketing', '0003_initial'),
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdeliverydate',
            name='transport_tracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportdeliverydatetracking'),
        ),
        migrations.AddField(
            model_name='supplieractualdeliverydate',
            name='supplier_po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_po.supplierpo'),
        ),
        migrations.AddField(
            model_name='supplieractualdeliverydate',
            name='supplier_po_delivery_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_po.supplierpodeliveryinvoice'),
        ),
        migrations.AddField(
            model_name='replacementquantitydeliverydate',
            name='replacement_expected_delivery_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_po.supplierdeliverydate'),
        ),
        migrations.AddField(
            model_name='replacementquantitydeliverydate',
            name='supplier_po_grn_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.supplierpogrnmaterial'),
        ),
        migrations.AddField(
            model_name='grnbatchnumbershade',
            name='batch_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.fabricgrnbatchnumber'),
        ),
        migrations.AddField(
            model_name='grnbatchnumbershade',
            name='split_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier_po.grnbatchnumbershade'),
        ),
        migrations.AddField(
            model_name='grnbatchnumbershade',
            name='supplier_po_shade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_po.supplierpofabricshade'),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='general_po_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.generalposupplier'),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='supplier_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirymaterialcode'),
        ),
        migrations.AddField(
            model_name='generalposupplier',
            name='general_po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.generalpo'),
        ),
        migrations.AddField(
            model_name='generalposupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.supplier'),
        ),
        migrations.AddField(
            model_name='generalpoquantity',
            name='general_po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.generalpo'),
        ),
        migrations.AddField(
            model_name='generalpoquantity',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpack'),
        ),
        migrations.AddField(
            model_name='generalpomaterialquantity',
            name='default_material_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_po.generalposuppliermaterialprice'),
        ),
        migrations.AddField(
            model_name='generalpomaterialquantity',
            name='general_po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.generalpo'),
        ),
        migrations.AddField(
            model_name='generalpomaterialquantity',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='generalpo',
            name='costing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='generalpo',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.plant'),
        ),
        migrations.AddField(
            model_name='generalpo',
            name='po_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='fabricgrnwidth',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.supplierpogrn'),
        ),
        migrations.AddField(
            model_name='fabricgrndetail',
            name='actual_width',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplier_po.fabricgrnwidth'),
        ),
        migrations.AddField(
            model_name='fabricgrndetail',
            name='color_tone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materials.fabriccolortone'),
        ),
        migrations.AddField(
            model_name='fabricgrndetail',
            name='grn_material_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.supplierpogrnmaterialdetail'),
        ),
        migrations.AddField(
            model_name='fabricgrnbatchnumber',
            name='grn_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier_po.supplierpogrnmaterial'),
        ),
        migrations.AddField(
            model_name='debitnotematerialdetail',
            name='debit_note_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.debitnotematerial'),
        ),
        migrations.AddField(
            model_name='debitnotematerialdetail',
            name='grn_material_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.supplierpogrnmaterialdetail'),
        ),
        migrations.AddField(
            model_name='debitnotematerial',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.debitnote'),
        ),
        migrations.AddField(
            model_name='debitnotematerial',
            name='supplier_po_grn_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_po.supplierpogrnmaterial'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='commercial_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.supplierpodeliveryinvoice'),
        ),
        migrations.AddConstraint(
            model_name='supplierpoclubmaterialshademapping',
            constraint=models.UniqueConstraint(fields=('po_club_shade', 'supplier_po_shade'), name='unique_po_club_shade_supplier_po_shade'),
        ),
        migrations.AddConstraint(
            model_name='supplieractualdeliverydate',
            constraint=models.UniqueConstraint(fields=('supplier_po', 'supplier_po_delivery_invoice'), name='unique_supplier_po_delivery_invoice'),
        ),
    ]
