# Generated by Django 4.2.13 on 2025-06-04 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0003_alter_approval_approval_name'),
        ('supplier_po', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpo',
            name='board_of_investment_registration_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_po_checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='contact_person',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.customer'),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='delivery_mode',
            field=models.CharField(choices=[('air', 'Air'), ('road', 'Road'), ('sea', 'Sea')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='email',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='payment_term',
            field=models.CharField(choices=[('100% tt in advance', '100% TT in Advance'), ('tt-advance', 'TT-Advance'), ('30 days credit', '30 Days Credit'), ('140 days credit', '140 Days Credit'), ('lc', 'LC')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.plant'),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_po_prepared_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='simplified_value_added_tax_registration_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='tems_of_delivery',
            field=models.CharField(choices=[('all', 'CIF-All'), ('cif', 'CIF-Sea'), ('fob', 'FOB'), ('ex-works', 'EX-Works')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='value_added_tax_registration_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
