# Generated by Django 4.2.9 on 2025-06-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_plant_warehouse_code'),
        ('supplier_po', '0003_supplierpo_board_of_investment_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpo',
            name='supplier_po_history_files',
            field=models.ManyToManyField(related_name='supplier_po_history_files', to='shared.fileattachment'),
        ),
    ]
