# Generated by Django 4.2.9 on 2025-06-19 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_po', '0004_supplierpo_supplier_po_history_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPOGeneralPOMaterialQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('general_po_material_quantity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier_po.generalpomaterialquantity')),
                ('supplier_po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier_po.supplierpo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
