# Generated by Django 4.2.13 on 2025-07-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_inhousematerial_grn_date_and_more'),
        ('supplier_po', '0005_supplierpogeneralpomaterialquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpo',
            name='supplier_po_file_with_po_wise_breakdown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_po_file_with_po_wise_breakdown', to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='supplierpogrnmaterialdetail',
            name='material_bin_allocation_details',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='supplierpo',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_email', 'Pending Email'), ('email_sent', 'Email Sent'), ('complete', 'Complete'), ('cancel', 'Cancel'), ('rejected', 'Rejected')], default='draft', max_length=200),
        ),
    ]
