# Generated by Django 4.2.13 on 2025-07-09 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_po', '0006_supplierpo_supplier_po_file_with_po_wise_breakdown_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierpo',
            old_name='tems_of_delivery',
            new_name='terms_of_delivery',
        ),
    ]
