# Generated by Django 5.0.6 on 2025-07-14 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_po', '0007_rename_tems_of_delivery_supplierpo_terms_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpomaterialquantity',
            name='guage_supplier_po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_po.supplierpo'),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='po_type',
            field=models.CharField(choices=[('guage_po', 'Guage PO'), ('supplier_po', 'Supplier PO')], default='supplier_po', max_length=200),
        ),
    ]
