# Generated by Django 5.0.6 on 2025-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_po', '0008_generalpomaterialquantity_guage_supplier_po_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpomaterialquantity',
            name='guage_supplier_po',
        ),
        migrations.RemoveField(
            model_name='supplierpo',
            name='po_type',
        ),
        migrations.AddField(
            model_name='generalposupplier',
            name='po_type',
            field=models.CharField(choices=[('greige_po', 'Greige PO'), ('supplier_po', 'Supplier PO')], default='supplier_po', max_length=200),
        ),
    ]
