# Generated by Django 4.2.9 on 2025-08-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_po', '0009_remove_generalpomaterialquantity_guage_supplier_po_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricgrndetail',
            name='actual_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fabricgrndetail',
            name='indicated_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='supplierpogrn',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('quantity_verification', 'Quantity Verification'), ('qa_verification', 'QA Verification'), ('grn_verification', 'GRN Verification'), ('grn_complete', 'GRN Complete'), ('grn_cancel', 'GRN Cancel'), ('grn_rejected', 'GRN Rejected')], default='draft', max_length=200),
        ),
    ]
