# Generated by Django 4.2.9 on 2025-09-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
        ('supplier_po', '0010_fabricgrndetail_actual_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='cif_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='cost_per_unit_type',
            field=models.CharField(choices=[('all', 'CIF-All'), ('cif', 'CIF-Sea'), ('fob', 'FOB'), ('ex-works', 'EX-Works')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='costing_unit',
            field=models.CharField(choices=[('per_meter', 'Per Metre'), ('per_centimeter', 'Per Centimetre'), ('per_millimeter', 'Per Millimetre'), ('per_yard', 'Per Yard'), ('per_inch', 'Per Inch'), ('per_feet', 'Per Feet'), ('per_piece', 'Per Piece'), ('per_2500_meters', 'Per Cone (2500 Metres)'), ('per_5000_meters', 'Per Cone (5000 Metres)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='cutting_width',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='cutting_width_unit',
            field=models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='ex_work_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='fob_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='minimum_order_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='minimum_order_quantity_units',
            field=models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='pay_mode',
            field=models.CharField(choices=[('100% tt in advance', '100% TT in Advance'), ('tt-advance', 'TT-Advance'), ('30 days credit', '30 Days Credit'), ('140 days credit', '140 Days Credit'), ('lc', 'LC')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='ship_mode',
            field=models.CharField(choices=[('air', 'Air'), ('road', 'Road'), ('sea', 'Sea')], default='sea', max_length=100),
        ),
        migrations.AddField(
            model_name='generalposuppliermaterialprice',
            name='transport_charges',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='generalposuppliermaterialprice',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
    ]
