# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('materials', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpurchaseorder',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='supplierinquirycostingversion',
            name='costing_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='supplierinquirycostingversion',
            name='supplier_inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquiry'),
        ),
        migrations.AddField(
            model_name='supplierbomfile',
            name='actual_po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='supplierbomfile',
            name='bom_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shared.fileattachment'),
        ),
    ]
