# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_po', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0002_initial'),
        ('marketing', '0002_initial'),
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbomfile',
            name='purchase_order_bom_suppliers',
            field=models.ManyToManyField(to='supplier_po.supplierdeliverydatequantity'),
        ),
        migrations.AddField(
            model_name='supplierbomfile',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shared.supplier'),
        ),
        migrations.AddField(
            model_name='selectedroll',
            name='marker_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.pomarkerpoint'),
        ),
        migrations.AddField(
            model_name='selectedroll',
            name='purchase_order_allocated_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorderallocatedmaterial'),
        ),
        migrations.AddField(
            model_name='selectedroll',
            name='roll_sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.rollsequence'),
        ),
        migrations.AddField(
            model_name='rollsequence',
            name='cut_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.markercutplan'),
        ),
        migrations.AddField(
            model_name='purchaseorderpackaginginstructionorderpack',
            name='po_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popack'),
        ),
        migrations.AddField(
            model_name='purchaseorderpackaginginstructionorderpack',
            name='po_pack_instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorderpackaginginstruction'),
        ),
        migrations.AddField(
            model_name='purchaseorderpackaginginstruction',
            name='carton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='purchaseorderpackaginginstruction',
            name='po_pack_packaging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorderpackaging'),
        ),
        migrations.AddField(
            model_name='purchaseorderpackaging',
            name='purchase_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderothercosttype',
            name='costing_other_cost_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.othercosttype'),
        ),
        migrations.AddField(
            model_name='purchaseorderothercosttype',
            name='other_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.othercost'),
        ),
        migrations.AddField(
            model_name='purchaseorderothercosttype',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderdeliverypack',
            name='po_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popack'),
        ),
        migrations.AddField(
            model_name='purchaseorderdeliverypack',
            name='purchase_order_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorderdelivery'),
        ),
        migrations.AddField(
            model_name='purchaseorderdelivery',
            name='outgoing_commercial_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.outgoingcommercialinvoice'),
        ),
        migrations.AddField(
            model_name='purchaseorderdelivery',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderbom',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='purchaseorderbom',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderbom',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorderbom',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='purchaseorderallocatedmaterial',
            name='in_house_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.inhousematerial'),
        ),
        migrations.AddField(
            model_name='purchaseorderallocatedmaterial',
            name='purchase_order_bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorderbom'),
        ),
        migrations.AddField(
            model_name='purchaseorderallocatedmaterial',
            name='shade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.poclubshade'),
        ),
        migrations.AddField(
            model_name='purchaseorderallocatedmaterial',
            name='width',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.fabricwidth'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='actual_po_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='costing_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.customer'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='marketing_costing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_purchase_order_set', to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='original_po_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.originalpoclub'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.plant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='uploaded_purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.uploadedpurchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posize',
            name='order_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.ordersize'),
        ),
        migrations.AddField(
            model_name='posize',
            name='po_club_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.actualpoclubsize'),
        ),
        migrations.AddField(
            model_name='posize',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='popackplacement',
            name='costing_pack_placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackplacement'),
        ),
        migrations.AddField(
            model_name='popackplacement',
            name='po_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='popackplacement',
            name='po_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popack'),
        ),
        migrations.AddField(
            model_name='popackplacement',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='popackothercost',
            name='costing_order_pack_other_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpackothercost'),
        ),
        migrations.AddField(
            model_name='popackothercost',
            name='other_cost_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.purchaseorderothercosttype'),
        ),
        migrations.AddField(
            model_name='popackothercost',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popack'),
        ),
        migrations.AddField(
            model_name='popackitemservice',
            name='costing_po_pack_item_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.packitemservice'),
        ),
        migrations.AddField(
            model_name='popackitemservice',
            name='po_pack_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popackitem'),
        ),
        migrations.AddField(
            model_name='popackitemplacement',
            name='costing_pack_item_placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackitemplacement'),
        ),
        migrations.AddField(
            model_name='popackitemplacement',
            name='po_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='popackitemplacement',
            name='po_pack_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popackitem'),
        ),
        migrations.AddField(
            model_name='popackitemplacement',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='popackitemoperation',
            name='costing_colorway_item_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderitemcolorwayoperation'),
        ),
        migrations.AddField(
            model_name='popackitemoperation',
            name='folder_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.foldertype'),
        ),
        migrations.AddField(
            model_name='popackitemoperation',
            name='machine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.machinetype'),
        ),
        migrations.AddField(
            model_name='popackitemoperation',
            name='po_pack_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popackitem'),
        ),
        migrations.AddField(
            model_name='popackitemoperation',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='popackitem',
            name='order_pack_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackitem'),
        ),
        migrations.AddField(
            model_name='popackitem',
            name='po_club_item_classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.poclubitemclassification'),
        ),
        migrations.AddField(
            model_name='popackitem',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.poitem'),
        ),
        migrations.AddField(
            model_name='popackitem',
            name='po_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popack'),
        ),
        migrations.AddField(
            model_name='popack',
            name='order_pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpack'),
        ),
        migrations.AddField(
            model_name='popack',
            name='po_colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pocolorway'),
        ),
        migrations.AddField(
            model_name='popack',
            name='po_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pocountry'),
        ),
        migrations.AddField(
            model_name='popack',
            name='po_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.posize'),
        ),
        migrations.AddField(
            model_name='popack',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='pomarkerpoint',
            name='po_marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pofabricmarker'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderitem'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='po_club_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.actualpoclubitem'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='pofabricmarkerplacement',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pofabricmarker'),
        ),
        migrations.AddField(
            model_name='pofabricmarkerplacement',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popackitemplacement'),
        ),
        migrations.AddField(
            model_name='pofabricmarkerplacement',
            name='related_marker_placements',
            field=models.ManyToManyField(to='marketing.pofabricmarkerplacement'),
        ),
        migrations.AddField(
            model_name='pofabricmarker',
            name='actual_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='pofabricmarker',
            name='attachments',
            field=models.ManyToManyField(to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='pofabricmarker',
            name='base_po_pack_item_marker_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.pofabricmarkerplacement'),
        ),
        migrations.AddField(
            model_name='pofabricmarker',
            name='derived_from_marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_width_markers', to='marketing.pofabricmarker'),
        ),
        migrations.AddField(
            model_name='pofabricmarker',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='pofabricmarker',
            name='marker_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.pocadmarkerupload'),
        ),
        migrations.AddField(
            model_name='pofabricmarker',
            name='parent_marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.pofabricmarker'),
        ),
        migrations.AddField(
            model_name='pofabricmarker',
            name='po_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='pofabricmarker',
            name='width',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.fabricwidth'),
        ),
        migrations.AddField(
            model_name='poembellishmentservicedetail',
            name='costing_embellishment_service_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.embellishmentservicedetail'),
        ),
        migrations.AddField(
            model_name='poembellishmentservicedetail',
            name='embellishment_attachment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='poembellishmentservicedetail',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='poembellishmentservicedetail',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.embellishmentsubtype'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayplacement',
            name='costing_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_country_colorway_placement_costing_material_set', to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayplacement',
            name='item_attribute_other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.orderplacement'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayplacement',
            name='po_colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pocolorway'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayplacement',
            name='po_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pocountry'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayplacement',
            name='po_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayplacement',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayitemplacement',
            name='costing_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_country_colorway_item_placement_costing_material_set', to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayitemplacement',
            name='item_attribute_other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.orderplacement'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayitemplacement',
            name='po_colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pocolorway'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayitemplacement',
            name='po_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pocountry'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayitemplacement',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.poitem'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayitemplacement',
            name='po_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='pocountrycolorwayitemplacement',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='pocountry',
            name='order_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercountry'),
        ),
        migrations.AddField(
            model_name='pocountry',
            name='po_club_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.actualpoclubcountry'),
        ),
        migrations.AddField(
            model_name='pocountry',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='pocolorwayitem',
            name='po_colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pocolorway'),
        ),
        migrations.AddField(
            model_name='pocolorwayitem',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.poitem'),
        ),
        migrations.AddField(
            model_name='pocolorway',
            name='order_colorway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='pocolorway',
            name='po_club_colorway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.actualpoclubcolorway'),
        ),
        migrations.AddField(
            model_name='pocolorway',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='poclubshade',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='poclubshade',
            name='po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='poclubshade',
            name='shade_swatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='poclubmaterialcolortone',
            name='acceptable_color_tones',
            field=models.ManyToManyField(to='materials.fabriccolortone'),
        ),
        migrations.AddField(
            model_name='poclubmaterialcolortone',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='poclubmaterialcolortone',
            name='po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='poclubleftovermaterial',
            name='assigned_customer_brand_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='poclubleftovermaterial',
            name='in_house_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.inhousematerial'),
        ),
        migrations.AddField(
            model_name='poclubleftovermaterial',
            name='po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='poclubitemclassification',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.country'),
        ),
        migrations.AddField(
            model_name='poclubitemclassification',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='poclubitemclassification',
            name='po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='poclubitemclassification',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.size'),
        ),
        migrations.AddField(
            model_name='poclubcutinstruction',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pofabricmarker'),
        ),
        migrations.AddField(
            model_name='pocadmarkerupload',
            name='area_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_file', to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='pocadmarkerupload',
            name='mini_marker_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minimarker_file', to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='packpackaging',
            name='costing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='packitemservice',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.packitemservice'),
        ),
        migrations.AddField(
            model_name='packitemservice',
            name='pack_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackitem'),
        ),
        migrations.AddField(
            model_name='packitemfabricconsumptionratio',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.packitemfabricconsumptionratio'),
        ),
        migrations.AddField(
            model_name='packitemfabricconsumptionratio',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='packitemfabricconsumptionratio',
            name='pack_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackitem'),
        ),
        migrations.AddField(
            model_name='packitemfabricconsumptionratio',
            name='supplier_inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquiry'),
        ),
        migrations.AddField(
            model_name='packinstructionorderpack',
            name='order_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpack'),
        ),
        migrations.AddField(
            model_name='packinstructionorderpack',
            name='pack_instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.packinstruction'),
        ),
        migrations.AddField(
            model_name='packinstruction',
            name='carton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='packinstruction',
            name='pack_packaging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.packpackaging'),
        ),
        migrations.AddField(
            model_name='othercosttype',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.othercosttype'),
        ),
        migrations.AddField(
            model_name='othercosttype',
            name='other_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.othercost'),
        ),
        migrations.AddField(
            model_name='othercosttype',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='originalpoclub',
            name='uploaded_purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.uploadedpurchaseorder'),
        ),
        migrations.AddField(
            model_name='orderversioncolorwaycountry',
            name='colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='orderversioncolorwaycountry',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderversioncolorwaycountry'),
        ),
        migrations.AddField(
            model_name='orderversioncolorwaycountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercountry'),
        ),
        migrations.AddField(
            model_name='orderversioncolorwaycountry',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='ordersizegroup',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.ordersizegroup'),
        ),
        migrations.AddField(
            model_name='ordersizegroup',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderinquiry'),
        ),
        migrations.AddField(
            model_name='ordersizegroup',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='marketing.ordersize'),
        ),
        migrations.AddField(
            model_name='ordersize',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.ordersize'),
        ),
        migrations.AddField(
            model_name='ordersize',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderinquiry'),
        ),
        migrations.AddField(
            model_name='ordersize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.size'),
        ),
        migrations.AddField(
            model_name='orderplacement',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderplacement'),
        ),
        migrations.AddField(
            model_name='orderplacement',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='orderplacement',
            name='item_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.itemattribute'),
        ),
        migrations.AddField(
            model_name='orderplacement',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.userdefinedmaterial'),
        ),
        migrations.AddField(
            model_name='orderplacement',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='orderpacksizegroup',
            name='colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='orderpacksizegroup',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpacksizegroup'),
        ),
        migrations.AddField(
            model_name='orderpacksizegroup',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercountry'),
        ),
        migrations.AddField(
            model_name='orderpacksizegroup',
            name='size_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordersizegroup'),
        ),
        migrations.AddField(
            model_name='orderpacksizegroup',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='orderpackplacementmaterialconsumption',
            name='attachments',
            field=models.ManyToManyField(to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='orderpackplacementmaterialconsumption',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpackplacementmaterialconsumption'),
        ),
        migrations.AddField(
            model_name='orderpackplacementmaterialconsumption',
            name='pack_placement_material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackplacementmaterial'),
        ),
        migrations.AddField(
            model_name='orderpackplacementmaterial',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpackplacementmaterial'),
        ),
        migrations.AddField(
            model_name='orderpackplacementmaterial',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='orderpackplacementmaterial',
            name='placement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackplacement'),
        ),
        migrations.AddField(
            model_name='orderpackplacement',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpackplacement'),
        ),
        migrations.AddField(
            model_name='orderpackplacement',
            name='item_attribute_other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.orderplacement'),
        ),
        migrations.AddField(
            model_name='orderpackplacement',
            name='order_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpack'),
        ),
        migrations.AddField(
            model_name='orderpackothercost',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpackothercost'),
        ),
        migrations.AddField(
            model_name='orderpackothercost',
            name='other_cost_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.othercosttype'),
        ),
        migrations.AddField(
            model_name='orderpackothercost',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpack'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacementpattern',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpackitemplacementpattern'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacementpattern',
            name='order_pack_item_placement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackitemplacement'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacementpattern',
            name='pattern_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacementmaterialconsumption',
            name='attachments',
            field=models.ManyToManyField(to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacementmaterialconsumption',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpackitemplacementmaterialconsumption'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacementmaterialconsumption',
            name='pack_item_placement_material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackitemplacementmaterial'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacementmaterial',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpackitemplacementmaterial'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacementmaterial',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacementmaterial',
            name='placement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackitemplacement'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacement',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpackitemplacement'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacement',
            name='item_attribute_other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.orderplacement'),
        ),
        migrations.AddField(
            model_name='orderpackitemplacement',
            name='order_pack_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpackitem'),
        ),
        migrations.AddField(
            model_name='orderpackitem',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpackitem'),
        ),
        migrations.AddField(
            model_name='orderpackitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderitem'),
        ),
        migrations.AddField(
            model_name='orderpackitem',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderpack'),
        ),
        migrations.AddField(
            model_name='orderpack',
            name='colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='orderpack',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderpack'),
        ),
        migrations.AddField(
            model_name='orderpack',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercountry'),
        ),
        migrations.AddField(
            model_name='orderpack',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordersize'),
        ),
        migrations.AddField(
            model_name='orderpack',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='orderitemcolorwayoperation',
            name='colorway_item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.colorwayitemtype'),
        ),
        migrations.AddField(
            model_name='orderitemcolorwayoperation',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderitemcolorwayoperation'),
        ),
        migrations.AddField(
            model_name='orderitemcolorwayoperation',
            name='folder_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.foldertype'),
        ),
        migrations.AddField(
            model_name='orderitemcolorwayoperation',
            name='item_variation_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.itemvariationoperation'),
        ),
        migrations.AddField(
            model_name='orderitemcolorwayoperation',
            name='machine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.machinetype'),
        ),
        migrations.AddField(
            model_name='orderitemcolorwayoperation',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='orderitemcolorwayoperation',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderinquiry'),
        ),
        migrations.AddField(
            model_name='orderinquirystylenumber',
            name='order_inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderinquiry'),
        ),
        migrations.AddField(
            model_name='orderinquiryprogram',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.brand'),
        ),
        migrations.AddField(
            model_name='orderinquiryprogram',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.customer'),
        ),
        migrations.AddField(
            model_name='orderinquiryprogram',
            name='season',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.season'),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.brand'),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderinquiry'),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.customer'),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.customerbranddepartment'),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='items',
            field=models.ManyToManyField(through='marketing.OrderItem', to='marketing.item'),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_order_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='order_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.orderinquiryprogram'),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='season',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.season'),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='size_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.sizecategory'),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='tech_packs',
            field=models.ManyToManyField(to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='orderinquiry',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist_order_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercountry',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.ordercountry'),
        ),
        migrations.AddField(
            model_name='ordercountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.country'),
        ),
        migrations.AddField(
            model_name='ordercountry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderinquiry'),
        ),
        migrations.AddField(
            model_name='ordercostingversion',
            name='attachments',
            field=models.ManyToManyField(to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='ordercostingversion',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_costing_version', to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='ordercostingversion',
            name='marketing_costing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='ordercostingversion',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercostingversion',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderinquiry'),
        ),
        migrations.AddField(
            model_name='ordercostingversion',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_costing_version', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercostingservicesupplierinquiry',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.ordercostingservicesupplierinquiry'),
        ),
        migrations.AddField(
            model_name='ordercostingservicesupplierinquiry',
            name='item_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.packitemservice'),
        ),
        migrations.AddField(
            model_name='ordercostingservicesupplierinquiry',
            name='order_costing_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='ordercostingservicesupplierinquiry',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='ordercostingcolorwaymaterialsupplierinquiry',
            name='colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='ordercostingcolorwaymaterialsupplierinquiry',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.ordercostingcolorwaymaterialsupplierinquiry'),
        ),
        migrations.AddField(
            model_name='ordercostingcolorwaymaterialsupplierinquiry',
            name='customer_brand_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='ordercostingcolorwaymaterialsupplierinquiry',
            name='order_costing_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='ordercostingcolorwaymaterialsupplierinquiry',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='ordercolorway',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='ordercolorway',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderinquiry'),
        ),
        migrations.AddField(
            model_name='markercutplan',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pofabricmarker'),
        ),
        migrations.AddField(
            model_name='itemvariationoperation',
            name='folder_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.foldertype'),
        ),
        migrations.AddField(
            model_name='itemvariationoperation',
            name='machine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.machinetype'),
        ),
        migrations.AddField(
            model_name='itemvariationoperation',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.itemvariation'),
        ),
        migrations.AddField(
            model_name='itemvariationoperation',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='colorway_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.colorwaycategory'),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='itemcountrycwcwycategorysizegroupfabricconsumptionratio',
            name='attachments',
            field=models.ManyToManyField(to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='itemcountrycwcwycategorysizegroupfabricconsumptionratio',
            name='colorway_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.colorwaycategory'),
        ),
        migrations.AddField(
            model_name='itemcountrycwcwycategorysizegroupfabricconsumptionratio',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.itemcountrycwcwycategorysizegroupfabricconsumptionratio'),
        ),
        migrations.AddField(
            model_name='itemcountrycwcwycategorysizegroupfabricconsumptionratio',
            name='customer_brand_fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='itemcountrycwcwycategorysizegroupfabricconsumptionratio',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='itemcountrycwcwycategorysizegroupfabricconsumptionratio',
            name='order_colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='itemcountrycwcwycategorysizegroupfabricconsumptionratio',
            name='order_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercountry'),
        ),
        migrations.AddField(
            model_name='itemcountrycwcwycategorysizegroupfabricconsumptionratio',
            name='order_size_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordersizegroup'),
        ),
        migrations.AddField(
            model_name='itemcountrycwcwycategorysizegroupfabricconsumptionratio',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='itemcountrycwcwycategorysizegroupfabricconsumptionratio',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='itemcolorwaytypefabricconsumptioncomplete',
            name='colorway_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.colorwaycategory'),
        ),
        migrations.AddField(
            model_name='itemcolorwaytypefabricconsumptioncomplete',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='itemcolorwaytypefabricconsumptioncomplete',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycolorwaycategoryfabricconsumptionratio',
            name='attachments',
            field=models.ManyToManyField(to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycolorwaycategoryfabricconsumptionratio',
            name='colorway_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.colorwaycategory'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycolorwaycategoryfabricconsumptionratio',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.itemcolorwaycolorwaycategoryfabricconsumptionratio'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycolorwaycategoryfabricconsumptionratio',
            name='customer_brand_fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycolorwaycategoryfabricconsumptionratio',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycolorwaycategoryfabricconsumptionratio',
            name='order_colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycolorwaycategoryfabricconsumptionratio',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycolorwaycategoryfabricconsumptionratio',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptionratio',
            name='attachments',
            field=models.ManyToManyField(to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptionratio',
            name='colorway_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.colorwaycategory'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptionratio',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.itemcolorwaycategoryfabricconsumptionratio'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptionratio',
            name='customer_brand_fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptionratio',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptionratio',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptionratio',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptioncomplete',
            name='colorway_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.colorwaycategory'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptioncomplete',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptioncomplete',
            name='order_colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='itemcolorwaycategoryfabricconsumptioncomplete',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.item'),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.userdefinedmaterial'),
        ),
        migrations.AddField(
            model_name='item',
            name='customer_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.customerbrand'),
        ),
        migrations.AddField(
            model_name='fabricwidthsupplier',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='fabricwidthsupplier',
            name='width',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.fabricwidth'),
        ),
        migrations.AddField(
            model_name='fabricwidth',
            name='actual_po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='fabricwidth',
            name='customer_brand_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='embellishmentservicedetail',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.embellishmentservicedetail'),
        ),
        migrations.AddField(
            model_name='embellishmentservicedetail',
            name='embellishment_attachment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='embellishmentservicedetail',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.embellishmentsubtype'),
        ),
        migrations.AddField(
            model_name='embellishmentservicedetail',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='colorwayitemtype',
            name='colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='colorwayitemtype',
            name='colorway_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.colorwaycategory'),
        ),
        migrations.AddField(
            model_name='colorwayitemtype',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.colorwayitemtype'),
        ),
        migrations.AddField(
            model_name='colorwayitemtype',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='colorwayitemtype',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.orderitem'),
        ),
        migrations.AddField(
            model_name='colorwayitemfabricconsumption',
            name='po_colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pocolorway'),
        ),
        migrations.AddField(
            model_name='colorwayitemfabricconsumption',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.poitem'),
        ),
        migrations.AddField(
            model_name='colorwayitemfabricconsumption',
            name='po_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='colorwayitemfabricconsumption',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='cadmarkerplacement',
            name='po_cad_marker_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.pocadmarkerupload'),
        ),
        migrations.AddField(
            model_name='cadmarkerplacement',
            name='po_pack_item_placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popackitemplacement'),
        ),
        migrations.AddField(
            model_name='actualpoclubsize',
            name='marketing_order_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_po_club_marketing_costing_order_size', to='marketing.ordersize'),
        ),
        migrations.AddField(
            model_name='actualpoclubsize',
            name='po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='actualpoclubsize',
            name='pre_costing_order_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_po_club_pre_costing_order_size_set', to='marketing.ordersize'),
        ),
        migrations.AddField(
            model_name='actualpoclubitem',
            name='marketing_costing_order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_po_club_marketing_costing_order_item', to='marketing.orderitem'),
        ),
        migrations.AddField(
            model_name='actualpoclubitem',
            name='po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='actualpoclubitem',
            name='pre_costing_order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_po_club_pre_costing_order_item_set', to='marketing.orderitem'),
        ),
        migrations.AddField(
            model_name='actualpoclubcountry',
            name='marketing_order_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_po_club_marketing_costing_order_country', to='marketing.ordercountry'),
        ),
        migrations.AddField(
            model_name='actualpoclubcountry',
            name='po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='actualpoclubcountry',
            name='pre_costing_order_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_po_club_pre_costing_order_country_set', to='marketing.ordercountry'),
        ),
        migrations.AddField(
            model_name='actualpoclubcolorway',
            name='marketing_order_colorway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_po_club_marketing_costing_order_colorway', to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='actualpoclubcolorway',
            name='po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='actualpoclubcolorway',
            name='pre_costing_order_colorway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_po_club_pre_costing_colorway_set', to='marketing.ordercolorway'),
        ),
        migrations.AddField(
            model_name='actualpoclub',
            name='marketing_costing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='marketing_costing_actual_po_club_set', to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='actualpoclub',
            name='original_po_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.originalpoclub'),
        ),
        migrations.AddField(
            model_name='actualpoclub',
            name='pre_costing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='actualpoclub',
            name='uploaded_purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.uploadedpurchaseorder'),
        ),
        migrations.AddField(
            model_name='actualclubbom',
            name='actual_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='actualclubbom',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderbom',
            constraint=models.UniqueConstraint(fields=('material', 'purchase_order'), name='unique_material_and_purchase_order'),
        ),
        migrations.AddField(
            model_name='popackitemwashservice',
            name='wash_service_attachment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='popackitemembellishmentservice',
            name='embellishment_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.poembellishmentservicedetail'),
        ),
        migrations.AddField(
            model_name='popackitemembellishmentservice',
            name='pack_item_embellishment_attachment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddConstraint(
            model_name='poitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'order_item'), name='unique_purchase_order_item'),
        ),
        migrations.AddConstraint(
            model_name='pocolorwayitem',
            constraint=models.UniqueConstraint(fields=('po_colorway', 'po_item'), name='unique_po_colorway_po_item'),
        ),
        migrations.AddConstraint(
            model_name='pocolorway',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'colorway'), name='unique_purchase_order_colorway'),
        ),
        migrations.AddField(
            model_name='packitemwashservice',
            name='wash_service_attachment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='packitemembellishmentservice',
            name='embellishment_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.embellishmentservicedetail'),
        ),
        migrations.AddField(
            model_name='packitemembellishmentservice',
            name='pack_item_embellishment_attachment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddConstraint(
            model_name='ordersize',
            constraint=models.UniqueConstraint(fields=('order', 'size'), name='unique_order_size'),
        ),
        migrations.AddConstraint(
            model_name='orderpacksizegroup',
            constraint=models.UniqueConstraint(fields=('size_group', 'colorway', 'country', 'version'), name='unique_pack_size_group_colorway_country'),
        ),
        migrations.AddConstraint(
            model_name='orderpackothercost',
            constraint=models.UniqueConstraint(fields=('pack', 'other_cost_type'), name='unique_pack_other_cost_type'),
        ),
        migrations.AddConstraint(
            model_name='orderpackitem',
            constraint=models.UniqueConstraint(fields=('pack', 'item'), name='unique_pack_item'),
        ),
        migrations.AddConstraint(
            model_name='orderpack',
            constraint=models.UniqueConstraint(fields=('size', 'colorway', 'country', 'version'), name='unique_pack_size_colorway_country'),
        ),
        migrations.AddConstraint(
            model_name='orderitemcolorwayoperation',
            constraint=models.UniqueConstraint(fields=('colorway_item_category', 'operation_name', 'version'), name='unique_colorway_item_type_operation'),
        ),
        migrations.AddConstraint(
            model_name='ordercountry',
            constraint=models.UniqueConstraint(fields=('order', 'country'), name='unique_order_country'),
        ),
        migrations.AddConstraint(
            model_name='ordercostingversion',
            constraint=models.UniqueConstraint(fields=('order', 'version'), name='unique_order_version'),
        ),
        migrations.AddConstraint(
            model_name='ordercolorway',
            constraint=models.UniqueConstraint(fields=('order', 'colorway'), name='unique_order_colorway'),
        ),
        migrations.AddConstraint(
            model_name='itemcolorwaytypefabricconsumptioncomplete',
            constraint=models.UniqueConstraint(fields=('colorway_category', 'item', 'version'), name='unique_order_cw_type_item_version'),
        ),
        migrations.AddConstraint(
            model_name='itemcolorwaycategoryfabricconsumptioncomplete',
            constraint=models.UniqueConstraint(fields=('order_colorway', 'colorway_category', 'item', 'version'), name='unique_order_colorway_cw_type_item_version'),
        ),
        migrations.AddConstraint(
            model_name='colorwayitemtype',
            constraint=models.UniqueConstraint(fields=('item', 'colorway'), name='unique_item_colorway'),
        ),
    ]
