# Generated by Django 5.0.6 on 2025-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercostingversion',
            name='version_state',
            field=models.CharField(choices=[('pending_materials_entry', 'Pending Entry of Materials'), ('pending_consumption_data_entry', 'Pending Entry of Consumption Ratios'), ('pending_material_supplier_selection', 'Pending Material Supplier Selection'), ('complete', 'Complete'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='pending_materials_entry', max_length=200),
        ),
    ]
