# Generated by Django 5.0.6 on 2025-06-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_ordercostingversion_version_state'),
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercostingversion',
            name='fabric_completion_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ordercostingversion',
            name='packaging_trim_completion_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ordercostingversion',
            name='sewing_trim_completion_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='CostingCompletedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('costing_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.userdefinedmaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
