# Generated by Django 5.0.6 on 2025-06-13 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_ordercostingversion_fabric_completion_date_and_more'),
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POClubCompletedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.userdefinedmaterial')),
                ('po_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
