# Generated by Django 4.2.13 on 2025-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_poclubcompletedmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderallocatedmaterial',
            name='used_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderallocatedmaterial',
            name='used_quantity_units',
            field=models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True),
        ),
    ]
