# Generated by Django 4.2.9 on 2025-08-25 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transportchangereason_and_more'),
        ('shared', '0008_customer_address'),
        ('marketing', '0007_purchaseorderallocatedmaterial_used_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderdelivery',
            name='delivery_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.port'),
        ),
        migrations.AddField(
            model_name='purchaseorderdelivery',
            name='shipping_method',
            field=models.CharField(choices=[('air', 'Air'), ('road', 'Road'), ('sea', 'Sea')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderdelivery',
            name='transport_delivery_date_tracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export', to='transport.transportdeliverydatetracking'),
        ),
        migrations.AddField(
            model_name='purchaseorderdeliverypack',
            name='shipped_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
