import uuid
from datetime import datetime
from random import random

from dateutil.relativedelta import relativedelta
from model_bakery import baker

from marketing.models import OrderInquiry
from materials.models import SupplierInquiryDetail, SupplierInquiry
from materials.tests.mixins.create_material_test_data_mixins import MaterialTestDataMixin
from shared.models import Season, CustomerBrand
from shared.utils import calculate_queryset_total_normalized_quantity
from supplier_po.models import GeneralPOSupplierMaterialPrice, GeneralPOMaterialQuantity, SupplierRequestedDeliveryDate, \
    SupplierDeliveryDateQuantity, SupplierDeliveryDate, SupplierActualDeliveryDate, SupplierPODeliveryInvoice, \
    SupplierPOInvoiceDeliveryNote, SupplierPODeliveryInvoicePackList, SupplierPOGRN, SupplierPOGRNMaterial, \
    GeneralPOSupplier, SupplierPO, SupplierPOGRNMaterialDetail


class SharedTestDataMixin(MaterialTestDataMixin):

    def update_object_kwargs(self, object, **kwargs):
        '''
            This will update any parameters given. Example: if "name" field is given for a Customer object,
            this function will update the name field generated by model baker.
        '''
        for key, value in kwargs.items():
            setattr(object, key, value)
        object.save()

    # shared app util functions
    def create_supplier(self, **kwargs):
        supplier = baker.make('shared.Supplier', **kwargs)
        return supplier

    def create_customer(self, **kwargs):
        customer = baker.make('shared.Customer', **kwargs)
        return customer

    def create_brand(self, **kwargs):
        brand = baker.make('shared.Brand', **kwargs)
        return brand

    def create_season(self, **kwargs):
        season = baker.make('shared.Season', **kwargs)
        return season

    def create_size_category(self, **kwargs):
        season = baker.make('shared.SizeCategory', **kwargs)
        return season

    def create_user(self, **kwargs):
        season = baker.make('shared.User', **kwargs)
        return season

    def get_or_create_customer_brand(self, customer, brand):
        object = CustomerBrand.objects.get_or_create(customer=customer, brand=brand)[0]
        return object

    # marketing app util functions
    def create_order_inquiry(self, **kwargs):
        customer = kwargs.get('customer', None)
        if not customer:
            customer = self.create_customer()
        brand = kwargs.get('brand', None)
        if not brand:
            brand = self.create_brand()
        customer_brand = self.get_or_create_customer_brand(customer, brand)

        data = {
            'customer': customer,
            'brand': brand,
            'season': self.create_season(customer_brand=customer_brand, name='Fall'),
            'year': 2024,
            'pack_type': 'single',
            'costing_method': 'common_price',
            'size_category': self.create_size_category(),
            'number_of_colorways': 2,
            'quantity_per_pack': 1,
            'style_number': 'abcdefg',
            'merchant': self.create_user(),
        }
        data = {**data, **kwargs}
        order_inquiry = baker.make('marketing.OrderInquiry', **data)
        return order_inquiry

    def create_order_costing_version(self, **kwargs):
        if not kwargs.get('order', None):
            kwargs['order'] = self.create_order_inquiry()
        version = baker.make('marketing.OrderCostingVersion', **kwargs)
        return version

    # supplier_po app util functions TODO - move this to a mixin in the supplier_po folder
    def create_general_po(self, **kwargs):
        general_po = baker.make('supplier_po.GeneralPO', **kwargs)
        return general_po
    
    def create_original_po_club(self, **kwargs):
        original_po_club = baker.make('marketing.OriginalPOClub', **kwargs)
        return original_po_club
    
    def create_po_club(self, **kwargs):
        if not kwargs.get('original_po_club', None):
            kwargs['original_po_club'] = self.create_original_po_club()
        po_club = baker.make('marketing.ActualPOClub', **kwargs)
        return po_club
    
    def create_purchase_order(self, **kwargs):
        if not kwargs.get('actual_po_club', None):
            kwargs['actual_po_club'] = self.create_po_club()
        if not kwargs.get('costing_version', None):
            kwargs['costing_version'] = self.create_order_costing_version()
        
        kwargs['style_number'] = kwargs['costing_version'].order.style_number
        kwargs['customer'] = kwargs['costing_version'].order.customer
        kwargs['original_po_club'] = kwargs['actual_po_club'].original_po_club
        kwargs['uploaded_purchase_order'] = kwargs['actual_po_club'].uploaded_purchase_order
        purchase_order = baker.make('marketing.PurchaseOrder', **kwargs)
        return purchase_order

    def create_general_po_supplier(self, **kwargs):
        po_supplier = baker.make('supplier_po.GeneralPOSupplier', **kwargs)
        return po_supplier

    def create_general_po_supplier_price(self, general_po_supplier, supplier_inquiry_detail, **kwargs):
        data = {
            'general_po_supplier': general_po_supplier,
            'supplier_material': supplier_inquiry_detail.supplier_inquiry_material_code,
            'supplier_inquiry_detail': supplier_inquiry_detail,
            'lead_time': 30,
            'costing_price': supplier_inquiry_detail.cost_per_unit,
            'costing_price_units': supplier_inquiry_detail.costing_unit,
            'order_price': supplier_inquiry_detail.cost_per_unit,
            'order_price_units': supplier_inquiry_detail.costing_unit,
            'excess_threshold': supplier_inquiry_detail.excess_threshold,
        }
        data = { **data, **kwargs}
        general_po_supplier_material_price = baker.make('supplier_po.GeneralPOSupplierMaterialPrice', **data)
        return general_po_supplier_material_price

    def create_general_po_material_quantity(self, general_po_supplier_material_price, **kwargs):
        data = {
            'general_po': general_po_supplier_material_price.general_po_supplier.general_po,
            'material': general_po_supplier_material_price.supplier_material.customer_brand_material,
            'quantity': 1000,
            'measuring_unit': general_po_supplier_material_price.supplier_material.customer_brand_material.material_normalized_measuring_unit,
            'order_quantity': 900,
            'order_quantity_units': general_po_supplier_material_price.supplier_material.customer_brand_material.material_normalized_measuring_unit,
            'default_material_supplier': general_po_supplier_material_price,
            'completed': True,
            **kwargs
        }
        general_po_material_quantity = baker.make('supplier_po.GeneralPOMaterialQuantity', **data)
        return general_po_material_quantity

    def create_supplier_delivery_date(self, general_po_supplier, **kwargs):
        date_after_month = datetime.today() + relativedelta(months=1)
        data = {
            'general_po_supplier': general_po_supplier,
            'confirmed_delivery_date': date_after_month,
            **kwargs
        }
        supplier_delivery_date = baker.make('supplier_po.SupplierDeliveryDate', **data)
        return supplier_delivery_date

    def create_supplier_delivery_date_quantity(self, general_po_material_quantity, general_po_supplier_material_price, **kwargs):
        data = {
            'general_po_material_quantity': general_po_material_quantity,
            'quantity': general_po_material_quantity.order_quantity,
            'quantity_units': general_po_material_quantity.order_quantity_units,
            'proforma_invoice_quantity': general_po_material_quantity.order_quantity,
            'proforma_invoice_quantity_units': general_po_material_quantity.order_quantity_units,
            'material_supplier': general_po_supplier_material_price,
            **kwargs
        }
        data['supplier_delivery_date'] = self.create_supplier_delivery_date(data['material_supplier'].general_po_supplier)
        supplier_delivery_date_quantity = baker.make('supplier_po.SupplierDeliveryDateQuantity', **data)
        return supplier_delivery_date_quantity

    def create_supplier_po_delivery_invoice(self, **kwargs):
        data = {
            'supplier_invoice_number': uuid.uuid4().hex.upper()[0:6],
            'ci_state': SupplierPODeliveryInvoice.OPEN_STATE,
            **kwargs
        }
        commercial_invoice = baker.make('supplier_po.SupplierPODeliveryInvoice', **data)
        return commercial_invoice

    def create_actual_delivery_date(self, supplier_delivery_date_quantity, **kwargs):
        commercial_invoice = self.create_supplier_po_delivery_invoice()

        data = {
            'delivery_date': datetime.today() + relativedelta(months=1),
            'supplier_po': supplier_delivery_date_quantity.material_supplier.general_po_supplier.supplier_po,
            'supplier_po_delivery_invoice': commercial_invoice,
            **kwargs
        }
        actual_delivery_date = baker.make('supplier_po.SupplierActualDeliveryDate', **data)

        supplier_delivery_date = supplier_delivery_date_quantity.supplier_delivery_date
        supplier_delivery_date.actual_delivery_date = actual_delivery_date
        supplier_delivery_date.save()

        return actual_delivery_date

    def create_supplier_po_delivery_note(self, commercial_invoice, **kwargs):

        data = {
            'supplier_po_delivery_invoice': commercial_invoice,
            'supplier_display_number': uuid.uuid4().hex.upper()[0:6],
            **kwargs
        }
        delivery_note = baker.make('supplier_po.SupplierPOInvoiceDeliveryNote', **data)
        return delivery_note

    def create_supplier_po_pack_list(self, delivery_note, **kwargs):

        data = {
            'supplier_po_delivery_note': delivery_note,
            'supplier_display_number': uuid.uuid4().hex.upper()[0:6],
            **kwargs
        }
        pack_list = baker.make('supplier_po.SupplierPODeliveryInvoicePackList', **data)
        return pack_list
    
    def create_supplier_po(self, general_po_supplier):
        data = {
            'general_po_supplier': general_po_supplier,
            'discount': 0,
        }
        supplier_po = baker.make('supplier_po.SupplierPO', **data)
        return supplier_po

    def create_supplier_po_grn(self, pack_list, supplier_po, **kwargs):
        data = {
            'supplier_po': supplier_po,
            'supplier_pack_list': pack_list
        }

        supplier_po_grn = baker.make('supplier_po.SupplierPOGRN', **data)
        return supplier_po_grn

    def create_supplier_po_grn_material(self, supplier_po_grn, supplier_inquiry_material_code, expected_quantity, expected_quantity_units, grn_price, **kwargs):
        data = {
            'supplier_po_grn': supplier_po_grn,
            'total_expected_quantity': expected_quantity,
            'total_expected_quantity_units': expected_quantity_units,
            'grn_material': supplier_inquiry_material_code,
            'grn_price': grn_price ,
            **kwargs
        }
        supplier_po_grn_material = baker.make('supplier_po.SupplierPOGRNMaterial', **data)
        return supplier_po_grn_material
    
    def create_supplier_po_grn_material_detail(self, supplier_po_grn_material, batch_number, shade,  **kwargs):
        data = {
            'supplier_po_grn_material': supplier_po_grn_material,
            'indicated_quantity': random()*50,
            'indicated_quantity_units': 'meters',
            'actual_quantity': random()*50,
            'actual_quantity_units': 'meters',
            'batch_number': batch_number,
            'shade': shade,
            **kwargs
        }

        supplier_po_grn_material_detail = baker.make('supplier_po.SupplierPOGRNMaterialDetail', **data)
        supplier_po_grn_material_detail.set_barcode()
        # supplier_po_grn_material_detail.calculate_defect_rate()
        return supplier_po_grn_material_detail