# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralServicePO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('quantity_verification', 'Quantity Verification'), ('ready_to_sent_po', 'Ready to sent PO'), ('po_sent', 'PO Sent'), ('closed', 'Closed'), ('canceled', 'Canceled')], max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralServicePODeliveryPOAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('quantity_units', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralServicePOService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('entity_id', models.PositiveIntegerField()),
                ('service_detail', models.JSONField()),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralServicePOServiceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('planned_send_date', models.DateField(null=True)),
                ('planned_send_quantity', models.FloatField()),
                ('planned_send_quantity_units', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
                ('actual_send_date', models.DateField(null=True)),
                ('actual_send_date_quantity', models.FloatField(null=True)),
                ('actual_send_date_quantity_units', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralServicePOSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('discount', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralServicePOSupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('entity_id', models.PositiveIntegerField()),
                ('service_detail', models.JSONField()),
                ('price', models.FloatField(null=True)),
                ('price_currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('lead_time', models.IntegerField(null=True)),
                ('costing_price', models.FloatField(null=True)),
                ('costing_price_units', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('total_price', models.FloatField()),
                ('total_price_currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('advance_payment', models.FloatField(null=True)),
                ('advance_payment_currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('advance_payment_due_date', models.DateField(null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_email', 'Pending Email'), ('email_sent', 'Email Sent'), ('complete', 'Complete'), ('cancel', 'Cancel')], default='draft', max_length=200)),
                ('advance_payment_outgoing_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.outgoingpayment')),
                ('service_po_supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_po.generalserviceposupplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
