# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shared', '0001_initial'),
        ('materials', '0002_initial'),
        ('marketing', '0002_initial'),
        ('service_po', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepo',
            name='supplier_po_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='generalserviceposupplierprice',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='generalserviceposupplierprice',
            name='general_service_po_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_po.generalserviceposupplier'),
        ),
        migrations.AddField(
            model_name='generalserviceposupplierprice',
            name='supplier_inquiry_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='generalserviceposupplier',
            name='general_service_po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_po.generalservicepo'),
        ),
        migrations.AddField(
            model_name='generalserviceposupplier',
            name='service_po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_po.servicepo'),
        ),
        migrations.AddField(
            model_name='generalserviceposupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.supplier'),
        ),
        migrations.AddField(
            model_name='generalserviceposervicedelivery',
            name='general_service_po_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_po.generalserviceposervice'),
        ),
        migrations.AddField(
            model_name='generalserviceposervicedelivery',
            name='general_service_po_supplier_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_po.generalserviceposupplierprice'),
        ),
        migrations.AddField(
            model_name='generalserviceposervice',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='generalserviceposervice',
            name='general_service_po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_po.generalservicepo'),
        ),
        migrations.AddField(
            model_name='generalservicepodeliverypoallocation',
            name='general_service_po_service_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_po.generalserviceposervicedelivery'),
        ),
        migrations.AddField(
            model_name='generalservicepodeliverypoallocation',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='generalservicepo',
            name='po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
    ]
