# Generated by Django 4.2.9 on 2025-06-23 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0005_plant_warehouse_code'),
        ('service_po', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepo',
            old_name='supplier_po_file',
            new_name='service_po_file',
        ),
        migrations.AddField(
            model_name='servicepo',
            name='board_of_investment_registration_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_po_checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='contact_person',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.customer'),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='email',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='payment_term',
            field=models.CharField(choices=[('100% tt in advance', '100% TT in Advance'), ('tt-advance', 'TT-Advance'), ('30 days credit', '30 Days Credit'), ('140 days credit', '140 Days Credit'), ('lc', 'LC')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.plant'),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='po_sent_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_po_prepared_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='proforma_invoice_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='service_po_history_files',
            field=models.ManyToManyField(related_name='service_po_history_files', to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='simplified_value_added_tax_registration_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicepo',
            name='value_added_tax_registration_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
