# Generated by Django 4.2.13 on 2025-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_po', '0003_rename_supplier_po_file_servicepo_service_po_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepo',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_email', 'Pending Email'), ('email_sent', 'Email Sent'), ('complete', 'Complete'), ('cancel', 'Cancel'), ('rejected', 'Rejected')], default='draft', max_length=200),
        ),
    ]
