# Generated by Django 5.0.6 on 2025-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_po', '0004_alter_servicepo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalserviceposupplier',
            name='payment_term',
            field=models.CharField(choices=[('100% tt in advance', '100% TT in Advance'), ('tt-advance', 'TT-Advance'), ('30 days credit', '30 Days Credit'), ('140 days credit', '140 Days Credit'), ('lc', 'LC')], default=None, max_length=100, null=True),
        ),
    ]
