# Generated by Django 4.2.9 on 2025-06-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportChangeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('trade_type', models.CharField(choices=[('import', 'Import'), ('export', 'Export'), ('all', 'All')], max_length=200)),
                ('location', models.CharField(choices=[('foreign', 'Foreign'), ('local', 'Local'), ('all', 'All')], max_length=200)),
                ('reason_category', models.CharField(choices=[('local_port', 'Local Port'), ('foreign_port', 'Foreign Port'), ('forwarder', 'Forwarder'), ('transport_mode', 'Transport Mode Category'), ('merge_to_existing_transport', 'Merge To Existing Transport')], max_length=200)),
                ('reason', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transportdeliverydatetracking',
            name='change_reasons',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='transportdeliverydatetracking',
            name='expected_delivery_date_delay_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transportdeliverydatetracking',
            name='foreign_port_date_delay_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transportdeliverydatetracking',
            name='local_port_date_delay_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transportdeliverydatetracking',
            name='spli_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportdeliverydatetracking'),
        ),
        migrations.AddField(
            model_name='transportdeliverydatetracking',
            name='vendor_shipping_date_delay_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transportfixedcharge',
            name='charge_currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100),
        ),
        migrations.AddField(
            model_name='transportperunitcharge',
            name='charge_currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100),
        ),
        migrations.AddField(
            model_name='transportvehicle',
            name='actual_delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transportvehicle',
            name='planned_delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transportvehicletracking',
            name='change_reasons',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='transportvehicletracking',
            name='split_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportvehicletracking'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='transport_cost_currency',
            field=models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100),
        ),
    ]
