# Generated by Django 4.2.9 on 2025-08-25 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_purchaseorderdelivery_delivery_port_and_more'),
        ('shared', '0008_customer_address'),
        ('supplier_po', '0010_fabricgrndetail_actual_weight_and_more'),
        ('transport', '0002_transportchangereason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerdelivery',
            name='purchase_order_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.purchaseorderdelivery'),
        ),
        migrations.AddField(
            model_name='freightforwarderwarehouse',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.address'),
        ),
        migrations.AddField(
            model_name='transportdeliverydatetracking',
            name='actual_customer_door_expected_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transportdeliverydatetracking',
            name='customer_door_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_door_address', to='shared.address'),
        ),
        migrations.AddField(
            model_name='transportdeliverydatetracking',
            name='customer_door_delivery_date_delay_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transportdeliverydatetracking',
            name='customer_door_expected_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='containerdelivery',
            name='supplier_delivery_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier_po.supplierdeliverydate'),
        ),
        migrations.AlterField(
            model_name='transportdeliverydatetracking',
            name='vendor_door_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_door_address', to='shared.address'),
        ),
        migrations.AlterField(
            model_name='transportdeliverydatetracking',
            name='vendor_door_expected_shipping_date',
            field=models.DateField(null=True),
        ),
    ]
