# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('amount', models.FloatField(null=True)),
                ('payment_date', models.DateField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomingPaymentDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('amount', models.FloatField(null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('reason', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingCommercialInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('amount', models.FloatField(null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('due_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('amount', models.FloatField(null=True)),
                ('payment_date', models.DateField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('payment_method', models.CharField(choices=[('pcl', 'PCL'), ('cash', 'Cash')], max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('pcl_settle_date', models.DateField(null=True)),
                ('pcl_create_date', models.DateField(null=True)),
                ('pcl_end_date', models.DateField(null=True)),
                ('interest_charge', models.FloatField(null=True)),
                ('interest_charge_currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('interest_rate', models.FloatField(null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete'), ('canceled', 'Canceled')], default='draft', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCLBankInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('total_amount_currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('pcl_threshold_amount', models.FloatField(null=True)),
                ('pcl_threshold_amount_currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('sent_to_bank', 'Send to bank'), ('closed', 'Closed')], default='draft', max_length=100)),
                ('pcl_facility_start_date', models.DateField(null=True)),
                ('pcl_facility_end_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCLInterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('interest_rate', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPODeliveryInvoicePCL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('entity_id', models.PositiveIntegerField()),
                ('amount', models.FloatField(null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=100)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('outgoing_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.outgoingpayment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCLBankInformationLinkedPOClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('pcl_bank_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.pclbankinformation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
