# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pclbankinformationlinkedpoclub',
            name='po_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.actualpoclub'),
        ),
        migrations.AddField(
            model_name='outgoingpayment',
            name='pcl_bank_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.pclbankinformation'),
        ),
    ]
