# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingcommercialinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shared.customer'),
        ),
        migrations.AddField(
            model_name='outgoingcommercialinvoice',
            name='invoice_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='incomingpaymentdeduction',
            name='incomming_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.incomingpayment'),
        ),
        migrations.AddField(
            model_name='incomingpayment',
            name='outgoing_commercial_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.outgoingcommercialinvoice'),
        ),
    ]
