# Generated by Django 4.2.9 on 2025-08-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingcommercialinvoice',
            name='incoterm',
            field=models.CharField(choices=[('all', 'CIF-All'), ('cif', 'CIF-Sea'), ('fob', 'FOB'), ('ex-works', 'EX-Works')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outgoingcommercialinvoice',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete'), ('canceled', 'Canceled')], default='draft', max_length=100),
        ),
    ]
