# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.db import migrations, models
import shared.shared_utils.reference_code_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBrandMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('marked_duplicate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shared.shared_utils.reference_code_utils.ModelReferenceCodeMixin),
        ),
        migrations.CreateModel(
            name='CustomerBrandMaterialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('customer_reference_code', models.CharField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shared.shared_utils.reference_code_utils.ModelReferenceCodeMixin),
        ),
        migrations.CreateModel(
            name='EmbellishmentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmbellishmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FabricColorTone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('color_1', models.CharField(max_length=100)),
                ('color_2', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('user_defined_material_data', models.JSONField(default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shared.shared_utils.reference_code_utils.ModelReferenceCodeMixin),
        ),
        migrations.CreateModel(
            name='GenericMaterialVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('user_defined_material_data', models.JSONField(default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shared.shared_utils.reference_code_utils.ModelReferenceCodeMixin),
        ),
        migrations.CreateModel(
            name='InHouseMaterialVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'IN Progress'), ('complete', 'Complete'), ('canceled', 'Canceled')], default='pending', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InHouseMaterialVerificationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('available_quantity', models.FloatField(null=True)),
                ('available_quantity_units', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
                ('usable_quantity', models.FloatField(null=True)),
                ('usable_quantity_units', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
                ('referance_material_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartialDeliveryTransferPackQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('quantity_units', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('hash_id', models.CharField(max_length=12, null=True)),
                ('has_supplier_feedback', models.BooleanField(default=False)),
                ('email_status', models.CharField(choices=[('queued_email', 'Queued Email'), ('pending_email', 'Pending Email'), ('pending_response', 'Pending Response'), ('received_and_processed', 'Received and Processed'), ('received_need_review', 'Review Needed'), ('not_applicable', 'Not Applicable')], default='pending_email', max_length=100)),
                ('total_requested_quantity', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierInquiryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('cutting_width', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('cutting_width_unit', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('costing_unit', models.CharField(choices=[('per_meter', 'Per Metre'), ('per_centimeter', 'Per Centimetre'), ('per_millimeter', 'Per Millimetre'), ('per_yard', 'Per Yard'), ('per_inch', 'Per Inch'), ('per_feet', 'Per Feet'), ('per_piece', 'Per Piece'), ('per_2500_meters', 'Per Cone (2500 Metres)'), ('per_5000_meters', 'Per Cone (5000 Metres)')], max_length=200, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=20, null=True)),
                ('fob_price', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True)),
                ('cif_price', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True)),
                ('transport_charges', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True)),
                ('ex_work_price', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('lead_time', models.IntegerField(blank=True, null=True)),
                ('minimum_order_quantity', models.FloatField(null=True)),
                ('minimum_order_quantity_units', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
                ('excess_threshold', models.FloatField(null=True)),
                ('ship_mode', models.CharField(choices=[('air', 'Air'), ('road', 'Road'), ('sea', 'Sea')], default='sea', max_length=100)),
                ('pay_mode', models.CharField(choices=[('100% tt in advance', '100% TT in Advance'), ('tt-advance', 'TT-Advance'), ('30 days credit', '30 Days Credit'), ('140 days credit', '140 Days Credit'), ('lc', 'LC')], max_length=200, null=True)),
                ('cost_per_unit_type', models.CharField(choices=[('all', 'CIF-All'), ('cif', 'CIF-Sea'), ('fob', 'FOB'), ('ex-works', 'EX-Works')], max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierInquiryEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierInquiryMaterialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('supplier_material_reference_code', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDefinedDropDownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('value', models.CharField(max_length=1000)),
                ('display_value', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDefinedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('sewing_trim', 'Sewing Trims'), ('packaging_trim', 'Packaging')], max_length=100)),
                ('material', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('mandatory', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('default_consumption_ratio', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('consumption_measurement_unit', models.CharField(choices=[('pieces_unit', 'Number of Pieces'), ('unit_of_length', 'Unit of Length')], max_length=200, null=True)),
                ('estimated_consumption_ratio_units', models.CharField(default=None, max_length=200, null=True)),
                ('has_shade', models.BooleanField(default=False)),
                ('size_dependent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserDefinedMaterialAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('attribute_type', models.CharField(choices=[('decimal', 'Decimal'), ('character', 'Character'), ('boolean', 'Boolean (True or False'), ('integer', 'Integer'), ('dropdown', 'Dropdown')], max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=1000)),
                ('display_order', models.IntegerField(default=0, null=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('is_material_variation', models.BooleanField(default=False)),
                ('po_editable', models.BooleanField(default=False)),
                ('is_grn_field', models.BooleanField(default=False)),
                ('size_field', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserDefinedMaterialDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('defect', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseMaterialTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('entity_id', models.PositiveIntegerField(null=True)),
                ('transfer_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('po_transfer', 'Purchase Order Transfer'), ('within_costing_transfer', 'Within Costing Transfer'), ('material_transfer', 'Material Transfer')], default='full', max_length=200)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('transfer_in_progress', 'Transfer in Progress'), ('complete', 'Complete'), ('canceled', 'Canceled')], default='draft', max_length=200)),
                ('material_verification_started', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseMaterialTransferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('quantity_units', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
                ('previous_quantity', models.FloatField(null=True)),
                ('previous_quantity_units', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
                ('full_quantity', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
