# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('materials', '0001_initial'),
        ('marketing', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousematerialtransferdetail',
            name='in_house_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.inhousematerial'),
        ),
        migrations.AddField(
            model_name='warehousematerialtransferdetail',
            name='previous_color_tone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materials.fabriccolortone'),
        ),
        migrations.AddField(
            model_name='warehousematerialtransferdetail',
            name='previous_shade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='marketing.poclubshade'),
        ),
        migrations.AddField(
            model_name='warehousematerialtransferdetail',
            name='warehouse_material_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.warehousematerialtransfer'),
        ),
        migrations.AddField(
            model_name='warehousematerialtransfer',
            name='entity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='warehousematerialtransfer',
            name='transfer_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.plantwarehouse'),
        ),
        migrations.AddField(
            model_name='userdefinedmaterialdefect',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.userdefinedmaterial'),
        ),
        migrations.AddField(
            model_name='userdefinedmaterialattribute',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.userdefinedmaterial'),
        ),
        migrations.AddConstraint(
            model_name='userdefinedmaterial',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_material_name'),
        ),
        migrations.AddField(
            model_name='userdefineddropdownoption',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.userdefinedmaterialattribute'),
        ),
        migrations.AddField(
            model_name='supplierinquirymaterialcode',
            name='customer_brand_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='supplierinquirymaterialcode',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.supplier'),
        ),
        migrations.AddField(
            model_name='supplierinquiryemail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.email'),
        ),
        migrations.AddField(
            model_name='supplierinquiryemail',
            name='supplier_inquiry',
            field=models.ManyToManyField(to='materials.supplierinquiry'),
        ),
        migrations.AddField(
            model_name='supplierinquirydetail',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.supplierinquirydetail'),
        ),
        migrations.AddField(
            model_name='supplierinquirydetail',
            name='supplier_inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquiry'),
        ),
        migrations.AddField(
            model_name='supplierinquirydetail',
            name='supplier_inquiry_material_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.supplierinquirymaterialcode'),
        ),
        migrations.AddField(
            model_name='supplierinquiry',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.supplierinquiry'),
        ),
        migrations.AddField(
            model_name='supplierinquiry',
            name='customer_brand_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterial'),
        ),
        migrations.AddField(
            model_name='supplierinquiry',
            name='item_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.packitemservice'),
        ),
        migrations.AddField(
            model_name='supplierinquiry',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.supplier'),
        ),
        migrations.AddField(
            model_name='supplierinquiry',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.ordercostingversion'),
        ),
        migrations.AddField(
            model_name='partialdeliverytransferpackquantity',
            name='po_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.popack'),
        ),
        migrations.AddField(
            model_name='partialdeliverytransferpackquantity',
            name='warehouse_material_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.warehousematerialtransfer'),
        ),
        migrations.AddField(
            model_name='inhousematerialverificationmaterial',
            name='color_tone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.fabriccolortone'),
        ),
        migrations.AddField(
            model_name='inhousematerialverificationmaterial',
            name='inhouse_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.inhousematerial'),
        ),
        migrations.AddField(
            model_name='inhousematerialverificationmaterial',
            name='inhouse_material_verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.inhousematerialverification'),
        ),
        migrations.AddField(
            model_name='inhousematerialverificationmaterial',
            name='referance_material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='inhousematerialverificationmaterial',
            name='shade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.poclubshade'),
        ),
        migrations.AddField(
            model_name='inhousematerialverification',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.plantwarehouse'),
        ),
        migrations.AddField(
            model_name='genericmaterialvariation',
            name='generic_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.genericmaterial'),
        ),
        migrations.AddField(
            model_name='genericmaterial',
            name='user_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.userdefinedmaterial'),
        ),
        migrations.AddField(
            model_name='embellishmentsubtype',
            name='embellishment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.embellishmenttype'),
        ),
        migrations.AddField(
            model_name='customerbrandmaterialcode',
            name='customer_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.customerbrand'),
        ),
        migrations.AddField(
            model_name='customerbrandmaterialcode',
            name='material_definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.genericmaterial'),
        ),
        migrations.AddField(
            model_name='customerbrandmaterial',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='customerbrandmaterial',
            name='material_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.customerbrandmaterialcode'),
        ),
        migrations.AddField(
            model_name='customerbrandmaterial',
            name='material_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.genericmaterialvariation'),
        ),
        migrations.AddConstraint(
            model_name='userdefinedmaterialattribute',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_user_defined_material_attribute_name'),
        ),
        migrations.AddConstraint(
            model_name='partialdeliverytransferpackquantity',
            constraint=models.UniqueConstraint(fields=('warehouse_material_transfer', 'po_pack'), name='unique_warehouse_material_transfer_and_po_pack'),
        ),
    ]
