# Generated by Django 4.2.13 on 2025-05-16 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('materials', '0002_initial'),
        ('supplier_po', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhousematerial',
            name='grn_material_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_po.supplierpogrnmaterialdetail'),
        ),
        migrations.AddField(
            model_name='inhousematerial',
            name='parent_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.inhousematerial'),
        ),
        migrations.AddField(
            model_name='inhousematerial',
            name='purchase_order_club_bom_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_po.supplierdeliverydatequantity'),
        ),
        migrations.AddField(
            model_name='inhousematerial',
            name='supplier_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materials.supplierinquirymaterialcode'),
        ),
        migrations.AddField(
            model_name='inhousematerial',
            name='warehouse_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.plantwarehouserackbin'),
        ),
        migrations.AddConstraint(
            model_name='foldertype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_folder_type_name'),
        ),
        migrations.AddField(
            model_name='email',
            name='attachments',
            field=models.ManyToManyField(to='shared.fileattachment'),
        ),
        migrations.AddField(
            model_name='customercontactperson',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.customer'),
        ),
        migrations.AddField(
            model_name='customerbranddepartment',
            name='customer_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.customerbrand'),
        ),
        migrations.AddField(
            model_name='customerbrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.brand'),
        ),
        migrations.AddField(
            model_name='customerbrand',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='brands',
            field=models.ManyToManyField(through='shared.CustomerBrand', to='shared.brand'),
        ),
        migrations.AddField(
            model_name='country',
            name='customer_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.customerbrand'),
        ),
        migrations.AddField(
            model_name='basetask',
            name='action_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basetask',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.locationcountry'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='customerbrand',
            constraint=models.UniqueConstraint(fields=('customer', 'brand'), name='unique_customer_brand'),
        ),
    ]
