# Generated by Django 5.0.6 on 2025-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_name',
            field=models.CharField(choices=[('left_over_assign_different_order', 'Review PO Club and check if it can be assigned'), ('purchase_order_reviewed', 'Review Purchase Order and approved'), ('grn_reviewed', 'Review GRN and and approved'), ('business_costing_approver_approval', 'Business Admin Costing Approval'), ('finance_costing_approver_approval', 'Finance Costing Approval')], max_length=500),
        ),
    ]
