# Generated by Django 4.2.9 on 2025-06-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_approval_approval_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='shared.address'),
        ),
        migrations.AddField(
            model_name='plant',
            name='billing_email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='billing_location_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='billing_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
