# Generated by Django 4.2.9 on 2025-06-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_plant_billing_address_plant_billing_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='warehouse_code',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
