# Generated by Django 4.2.13 on 2025-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_plant_warehouse_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhousematerial',
            name='grn_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='plantwarehouserackbin',
            name='bin_number',
            field=models.CharField(default='Fill Data', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='approval_name',
            field=models.CharField(choices=[('left_over_assign_different_order', 'Review PO Club and check if it can be assigned'), ('purchase_order_reviewed', 'Review Purchase Order and approved'), ('grn_reviewed', 'Review GRN and and approved'), ('business_costing_approver_approval', 'Business Admin Costing Approval'), ('finance_costing_approver_approval', 'Finance Costing Approval'), ('supplier_po_approval', 'Supplier PO Approval'), ('service_po_approval', 'Service PO Approval')], max_length=500),
        ),
    ]
