# Generated by Django 4.2.9 on 2025-08-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_inhousematerial_grn_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_name',
            field=models.CharField(choices=[('left_over_assign_different_order', 'Review PO Club and check if it can be assigned'), ('purchase_order_reviewed', 'Review Purchase Order and approved'), ('grn_approval', 'Review GRN and and approved'), ('business_costing_approver_approval', 'Business Admin Costing Approval'), ('finance_costing_approver_approval', 'Finance Costing Approval'), ('supplier_po_approval', 'Supplier PO Approval'), ('service_po_approval', 'Service PO Approval')], max_length=500),
        ),
    ]
