# Generated by Django 4.2.9 on 2025-09-10 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('remarks', models.TextField(null=True)),
                ('issue_date', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete')], default='draft', max_length=200)),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='users',
            field=models.ManyToManyField(related_name='plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approval_name',
            field=models.CharField(choices=[('left_over_assign_different_order', 'Review PO Club and check if it can be assigned'), ('purchase_order_reviewed', 'Review Purchase Order and approved'), ('grn_approval', 'Review GRN and and approved'), ('business_costing_approver_approval', 'Business Admin Costing Approval'), ('finance_costing_approver_approval', 'Finance Costing Approval'), ('supplier_po_approval', 'Supplier PO Approval'), ('service_po_approval', 'Service PO Approval'), ('bom_change_request_approval', 'BOM Change Request Approval')], max_length=500),
        ),
        migrations.CreateModel(
            name='IssueNoteMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('issue_quantity', models.FloatField(null=True)),
                ('issue_quantity_units', models.CharField(choices=[('meters', 'Meters'), ('centimeters', 'Centimetres'), ('millimeters', 'Millimetres'), ('yards', 'Yards'), ('inches', 'Inches'), ('feets', 'Feet'), ('pieces', 'Pieces'), ('2500_meters', 'Cone (2500 Meters)'), ('5000_meters', 'Cone (5000 Meters)')], max_length=100, null=True)),
                ('in_house_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.inhousematerial')),
                ('issue_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shared.issuenote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(through='shared.CustomerMerchant', to=settings.AUTH_USER_MODEL),
        ),
    ]
