# Generated by Django 5.0.6 on 2025-09-15 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_bomchangerequest_bomchangerequestchangetype_and_more'),
        ('shared', '0009_issuenote_plant_users_alter_approval_approval_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhousematerial',
            name='po_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.actualpoclub'),
        ),
    ]
