
ADMIN_ROLE = 'ADMIN'

MERCHANT_ROLE = 'MERCHANT'

MERCHANT_ADMIN_ROLE = 'MERCHANT_ADMIN'

CAD_USER_ROLE = 'CAD_USER'

CAD_ADMIN_ROLE = 'CAD_ADMIN'

IE_USER_ROLE = 'IE_USER'

TRANSPORT_ADMIN_ROLE = 'TRANSPORT_ADMIN'

TRANSPORT_USER_ROLE = 'TRANSPORT_USER'

BUSINESS_ADMIN_ROLE = 'BUSINESS_ADMIN'

STORES_USER_ROLE = 'STORES_USER'

STORES_ADMIN_ROLE = 'STORES_ADMIN'

STORES_EDITOR_ROLE = 'STORES_EDITOR'

STORES_MANAGER_ROLE = 'STORES_MANAGER'

FABRIC_INSPECTION_USER_ROLE = 'FABRIC_INSPECTION_USER'

FINANCE_ADMIN_ROLE = 'FINANCE_ADMIN'

FINANCE_USER_ROLE = 'FINANCE_USER'

FINANCE_READ_ROLE = 'FINANCE_READ'

BUSINESS_ADMIN_COSTING_APPROVER = 'BUSINESS_ADMIN_COSTING_APPROVER'

FINANCE_COSTING_APPROVER = 'FINANCE_COSTING_APPROVER'

SUPPLIER_PO_APPROVER = 'SUPPLIER_PO_APPROVER'

SERVICE_PO_APPROVER = 'SERVICE_PO_APPROVER'

GRN_APPROVER = 'GRN_APPROVER'

BOM_CHANGE_REQUEST_APPROVER = 'BOM_CHANGE_REQUEST_APPROVER'

ALL_USER_ROLES = '*' # This is not a role it is used to specify if an api has access to all users


ALL_ROLES = [
    ADMIN_ROLE,
    MERCHANT_ROLE,
    MERCHANT_ADMIN_ROLE,
    CAD_USER_ROLE,
    CAD_ADMIN_ROLE,
    IE_USER_ROLE,
    TRANSPORT_ADMIN_ROLE,
    TRANSPORT_USER_ROLE,
    BUSINESS_ADMIN_ROLE,
    STORES_USER_ROLE,
    STORES_ADMIN_ROLE,
    STORES_EDITOR_ROLE,
    STORES_MANAGER_ROLE,
    FABRIC_INSPECTION_USER_ROLE,
    FINANCE_ADMIN_ROLE,
    FINANCE_USER_ROLE,
    FINANCE_READ_ROLE,
    BUSINESS_ADMIN_COSTING_APPROVER,
    FINANCE_COSTING_APPROVER,
    SUPPLIER_PO_APPROVER,
    SERVICE_PO_APPROVER,
    GRN_APPROVER,
    BOM_CHANGE_REQUEST_APPROVER
] # Add every role added in here
